sudo: false
language: ruby
before_install:
  - gem update --system
  - gem install bundler
rvm:
  - 2.6.1
cache:
  bundler: true
  directories:
    - node_modules
  yarn: true

install:
  - bundle install
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn
script:
  - bundle exec rails webpacker:compile
  - bundle exec rake