sudo: false
language: ruby
before_install:
  - gem update --system
  - gem install bundler
rvm:
  - 2.6.1
cache:
  bundler: true
  directories:
    - node_modules
  yarn: true

install:
  - bundle install
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn
addons:
  postgresql: "9.6"

before_script:
  - bin/yarn
  - bundle exec rake db:create db:test:prepare
  - bin/rails db:migrate RAILS_ENV=test

script:
  - yarn test
  - bundle exec rspec spec

after_success:
  - bundle exec rake assets:precompile