sudo: required
language: ruby
before_install:
  - gem update --system
  - gem install bundler
rvm:
  - 2.6.1
cache:
  bundler: true
  directories:
    - node_modules
  yarn: true

install:
  - bundle install
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn
addons:
  postgresql: "9.6"

before_script:
  - bin/yarn
  - bundle exec rake db:create db:test:prepare
  - bin/rails db:migrate RAILS_ENV=test

script:
  - yarn test
  - bundle exec rspec spec
  - bundle exec rake assets:precompile

after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL