default:
  plugins:
    - image
    - link
    - preview
    - searchreplace
    - autolink
    - directionality
    - fullscreen
    - image
    - media
    - template
    - code
    - codesample
    - table
    - charmap
    - hr
    - anchor
    - toc
    - insertdatetime
    - advlist
    - lists
    - wordcount
    - imagetools
    - textpattern
    - help
  toolbar: formatselect | spellchecker | bold italic strikethrough forecolor backcolor | link code | alignleft aligncenter alignright alignjustify  | numlist bullist outdent indent  | removeformat
  spellchecker_language: 'pl'
  language: 'pl'
  browser_spellcheck: true

alternate:
  selector: textarea.table-editor
  toolbar: formatselect | spellchecker | bold italic strikethrough forecolor backcolor | link code | alignleft aligncenter alignright alignjustify  | numlist bullist outdent indent  | removeformat
  browser_spellcheck: true
  plugins:
    - image
    - preview
    - searchreplace
    - autolink
    - directionality
    - fullscreen
    - image
    - link
    - media
    - template
    - codesample
    - table
    - charmap
    - hr
    - anchor
    - toc
    - insertdatetime
    - advlist
    - lists
    - wordcount
    - imagetools
    - textpattern
    - help
  language: 'pl'
  spellchecker_language: 'pl'